remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Carla Karina Zapata Rodriguez
submodulo: Introducción a la programación
periodo: 2023-2
url_foto: gs://proyecto-de-desarrollo-li.appspot.com/the.jpeg